
#
# Example wadl2rst config file
#
# For instructions on installing the script and updating this configuration file, 
# see https://github.rackspace.com/Product-DevOps/wadl2rst. 

src/wadl/image-2.0.wadl:
    title: 1
    output directory: /rst/dev-guide/api-operations 

src/wadl/image-schemas-2.0.wadl:
    title: 1
    output directory: /rst/dev-guide/api-operations
